---
- name: Configure Jenkins Server (WAR-based) on Amazon Linux 2023
  hosts: jenkins
  become: yes
  tasks:

    - name: Update all packages
      yum:
        name: "*"
        state: latest

    - name: Install Java 17 (Amazon Corretto) for AL2023
      yum:
        name:
          - java-17-amazon-corretto
          - java-17-amazon-corretto-devel
        state: present

    - name: Ensure JAVA_HOME is set for all users
      copy:
        dest: /etc/profile.d/java.sh
        content: |
          export JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto.x86_64
          export PATH=$JAVA_HOME/bin:$PATH
        owner: root
        group: root
        mode: "0644"

    - name: Ensure wget is installed
      yum:
        name: wget
        state: present

    - name: Create Jenkins directory
      file:
        path: /opt/jenkins
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: "0755"

    - name: Download Jenkins WAR
      get_url:
        url: https://get.jenkins.io/war-stable/2.479.1/jenkins.war
        dest: /opt/jenkins/jenkins.war
        mode: "0755"
        owner: ec2-user
        group: ec2-user

    - name: Create systemd service for Jenkins
      copy:
        dest: /etc/systemd/system/jenkins.service
        content: |
          [Unit]
          Description=Jenkins Continuous Integration Server
          After=network.target

          [Service]
          User=ec2-user
          Environment="JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto.x86_64"
          ExecStart=/usr/bin/java -jar /opt/jenkins/jenkins.war --httpPort=8080
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target
        owner: root
        group: root
        mode: "0644"

    - name: Reload systemd
      command: systemctl daemon-reload

    - name: Start and enable Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes

- name: Configure Docker and Nginx Server
  hosts: docker_nginx
  become: yes
  tasks:

    - name: Update all packages
      yum:
        name: "*"
        state: latest

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes

